In [17]:
from basketball_reference_web_scraper.data import Team
from basketball_reference_web_scraper import client
from basketball_reference_web_scraper import *
import pandas as pd

In [18]:
df = pd.DataFrame(client.season_schedule(season_end_year=2020))

In [19]:
df

,start_time,away_team,home_team,away_team_score,home_team_score
0,2019-10-23 00:00:00+00:00,Team.NEW_ORLEANS_PELICANS,Team.TORONTO_RAPTORS,122.0,130.0
1,2019-10-23 02:30:00+00:00,Team.LOS_ANGELES_LAKERS,Team.LOS_ANGELES_CLIPPERS,102.0,112.0
2,2019-10-23 23:00:00+00:00,Team.CHICAGO_BULLS,Team.CHARLOTTE_HORNETS,125.0,126.0
3,2019-10-23 23:00:00+00:00,Team.DETROIT_PISTONS,Team.INDIANA_PACERS,119.0,110.0
4,2019-10-23 23:00:00+00:00,Team.CLEVELAND_CAVALIERS,Team.ORLANDO_MAGIC,85.0,94.0
...,...,...,...,...,...
1224,2020-04-15 23:30:00+00:00,Team.NEW_ORLEANS_PELICANS,Team.SAN_ANTONIO_SPURS,NaN,NaN
1225,2020-04-15 23:30:00+00:00,Team.INDIANA_PACERS,Team.WASHINGTON_WIZARDS,NaN,NaN
1226,2020-04-16 02:00:00+00:00,Team.LOS_ANGELES_LAKERS,Team.PHOENIX_SUNS,NaN,NaN
1227,2020-04-16 02:00:00+00:00,Team.LOS_ANGELES_CLIPPERS,Team.PORTLAND_TRAIL_BLAZERS,NaN,NaN
1228,2020-04-16 02:00:00+00:00,Team.GOLDEN_STATE_WARRIORS,Team.SACRAMENTO_KINGS,NaN,NaN

In [20]:
df['day'] = df['start_time'][0].day

In [21]:
df['month'] = df['start_time'][0].month

In [22]:
df['year'] = df['start_time'][0].year

In [23]:
df['date'] = df['start_time'][0].date

In [24]:
for i in df.index:
    df['day'][i] = df['start_time'][i].day
    df['month'][i] = df['start_time'][i].month
    df['year'][i] = df['start_time'][i].year
#     df['date'][i] =

/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [12]:
df['date'][0] = df[df['year'][0],df['month'][0],df['day'][0]]

KeyError: (2019, 10, 23)

In [26]:
df['date'][1] = df['start_time'][0].date

/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [28]:
df['date']

0       <built-in method date of Timestamp object at 0...
1       <built-in method date of Timestamp object at 0...
2       <built-in method date of Timestamp object at 0...
3       <built-in method date of Timestamp object at 0...
4       <built-in method date of Timestamp object at 0...
                              ...
1224    <built-in method date of Timestamp object at 0...
1225    <built-in method date of Timestamp object at 0...
1226    <built-in method date of Timestamp object at 0...
1227    <built-in method date of Timestamp object at 0...
1228    <built-in method date of Timestamp object at 0...
Name: date, Length: 1229, dtype: object

In [10]:
pd.DataFrame(client.team_box_scores(df['day'][0],df['month'][0],df['year'][0]))

,team,outcome,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points
0,Team.MINNESOTA_TIMBERWOLVES,Outcome.WIN,265,46,108,13,43,22,28,12,40,23,9,4,13,22,127
1,Team.BROOKLYN_NETS,Outcome.LOSS,265,48,101,15,34,15,26,10,38,19,8,9,16,30,126
2,Team.CHICAGO_BULLS,Outcome.LOSS,240,49,105,9,30,18,22,20,29,25,11,4,10,20,125
3,Team.CHARLOTTE_HORNETS,Outcome.WIN,240,45,88,23,44,13,16,9,32,28,3,4,19,18,126
4,Team.WASHINGTON_WIZARDS,Outcome.LOSS,240,37,93,11,41,15,18,11,36,26,6,3,17,32,100
5,Team.DALLAS_MAVERICKS,Outcome.WIN,240,35,76,11,36,27,33,5,41,17,6,5,19,22,108
6,Team.DETROIT_PISTONS,Outcome.WIN,240,41,78,11,24,26,33,10,35,26,5,6,18,21,119
7,Team.INDIANA_PACERS,Outcome.LOSS,240,41,89,8,21,20,24,10,26,26,8,6,15,28,110
8,Team.MEMPHIS_GRIZZLIES,Outcome.LOSS,240,38,89,5,32,20,30,9,31,22,9,7,24,31,101
9,Team.MIAMI_HEAT,Outcome.WIN,240,40,85,7,18,33,39,11,40,18,9,8,21,33,120
10,Team.CLEVELAND_CAVALIERS,Outcome.LOSS,240,33,88,9,34,10,15,10,44,20,8,2,16,15,85
11,Team.ORLANDO_MAGIC,Outcome.WIN,240,37,86,9,30,11,19,7,39,24,12,4,13,18,94
12,Team.BOSTON_CELTICS,Outcome.LOSS,240,33,90,7,26,20,34,10,31,18,4,2,10,29,93
13,Team.PHILADELPHIA_76ERS,Outcome.WIN,240,37,85,7,29,26,36,12,50,24,6,7,15,34,107
14,Team.SACRAMENTO_KINGS,Outcome.LOSS,240,34,87,10,29,17,26,12,35,17,5,5,26,24,95
15,Team.PHOENIX_SUNS,Outcome.WIN,240,49,98,11,33,15,18,9,35,31,13,9,14,25,124
16,Team.DENVER_NUGGETS,Outcome.WIN,240,34,81,18,32,22,27,11,34,24,11,4,19,23,108
17,Team.PORTLAND_TRAIL_BLAZERS,Outcome.LOSS,240,36,87,7,28,21,23,13,35,13,9,4,20,25,100
18,Team.NEW_YORK_KNICKS,Outcome.LOSS,240,44,94,10,30,13,18,5,34,24,16,1,14,32,111
19,Team.SAN_ANTONIO_SPURS,Outcome.WIN,240,42,83,7,21,29,36,10,41,22,6,5,21,18,120
20,Team.OKLAHOMA_CITY_THUNDER,Outcome.LOSS,240,32,83,10,27,21,31,7,41,15,5,4,13,23,95
21,Team.UTAH_JAZZ,Outcome.WIN,240,40,90,6,24,14,20,11,38,15,4,5,11,31,100

In [ ]:
df_box_scores = client.team_box_scores(day = df['day'][i], month = df['month'][i], year = df['year'][i])

In [49]:
dfdvp = pd.read_html('https://basketballmonster.com/dfsdvp.aspx')[0]

In [50]:
dfdvp

                 Team   g    All    PG    SG    SF    PF     C
   Unnamed: 0_level_1 Avg  223.9  46.3  41.5  40.2  44.1  51.8
0              vs ATL  56  241.1  47.0  44.1  46.3  48.4  55.2
1              vs CLE  54  238.4  51.3  45.2  43.2  45.1  53.2
2              vs WAS  53  235.5  50.1  42.7  42.5  45.6  55.0
3              vs GSW  55  233.3  49.6  43.6  42.8  44.5  52.9
4              vs POR  56  232.8  49.5  41.0  41.0  47.2  54.7
5              vs HOU  54  231.8  47.3  44.0  41.9  47.5  51.5
6              vs NOR  55  231.0  50.6  41.9  40.8  45.7  53.0
7              vs MEM  54  230.8  46.5  43.6  41.8  45.1  53.6
8              vs MIN  53  229.4  47.6  43.7  41.3  45.3  51.9
9              vs CHA  54  229.4  44.3  42.2  40.2  46.4  56.4
10             vs PHO  55  227.0  46.9  42.7  40.6  43.3  53.3
11             vs CHI  55  226.9  41.9  38.6  40.7  49.0  56.5
12             vs SAS  54  225.9  47.3  42.5  40.3  45.2  50.5
13             vs DET  57  225.7  44.8  41.5  39.6  45.2  54.3
14             vs BKN  53  224.5  49.3  40.3  38.4  41.7  55.3
15             vs LAC  55  224.5  45.9  41.2  39.7  43.6  53.5
16             vs NYK  55  223.5  47.8  41.2  38.5  46.2  49.5
17             vs MIL  54  220.6  45.9  40.2  39.5  43.4  52.0
18             vs SAC  54  220.5  46.7  42.7  41.1  40.5  49.2
19             vs DAL  55  219.7  45.6  40.7  40.1  43.0  50.6
20             vs TOR  55  219.4  43.9  41.9  41.8  44.7  47.1
21             vs ORL  55  216.7  44.9  40.2  39.5  44.9  47.3
22             vs MIA  54  215.1  42.8  40.8  39.2  42.1  50.1
23             vs DEN  55  214.9  44.6  38.9  37.9  42.1  50.7
24             vs UTA  54  214.7  45.1  39.4  37.4  41.9  51.3
25             vs BOS  54  213.9  42.7  40.0  38.6  43.4  49.6
26             vs IND  55  213.8  44.6  40.3  35.9  40.6  52.4
27             vs OKC  55  213.5  45.5  39.2  37.1  40.1  51.0
28             vs LAL  53  212.9  46.9  40.4  39.4  40.0  46.4
29             vs PHI  55  208.6  42.7  40.1  38.9  41.0  46.1